version: 0.0
os: linux

files:
 - source: /
   destination: /home/ubuntu/REPLACE_PROJECT_NAME-deploy

permissions:
 - object: /
   pattern: "**"
   owner: ubuntu
   group: ubuntu

hooks:
  AfterInstall:
    - location: stop_server.sh
      timeout: 300
      runas: root
    - location: start_server.sh
      timeout: 400
      runas: root
