version: '3.3'

services:

  blog_REPLACE_PROJECT_NAME:
    image: REPLACE_IMAGE_NAME
    networks:
      - traefik_proxy
    secrets:
      - mysql_host
      - mysql_passwd
      - mysql_user
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_passwd
      WORDPRESS_DB_HOST_FILE: /run/secrets/mysql_host
      WORDPRESS_DB_USER_FILE: /run/secrets/mysql_user
      WORDPRESS_DB_NAME: REPLACE_PROJECT_NAME
    volumes:
      - REPLACE_PROJECT_NAME_vol:/var/www/html/wp-content
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.backend=blog_REPLACE_PROJECT_NAME"
        - "traefik.frontend.rule=Host:REPLACE_URL_TEST"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_proxy"
        - "traefik.backend.loadbalancer.sticky=true"
        - "traefik.frontend.passHostHeader=true"
      restart_policy:
        condition: on-failure
 
networks:
  traefik_proxy:
    external: true

volumes:
  REPLACE_PROJECT_NAME_vol:

secrets:
  mysql_host:
    external: true
  mysql_passwd:
    external: true
  mysql_user:
    external: true
     

