version: '3.1'

services:

  web_:
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: password      
    volumes:
      - ./themes:/var/www/html/wp-content/themes   
    links: 
      - mysql

  mysql:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 1000:80
    environment:
      - MYSQL_ROOT_PASSWORD:password
    links: 
      - mysql:db
